services:
  mongodb:
    image: mongo:4.4.6
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask-app
    volumes:
      - .:/app
    environment:
      - MONGO_URI=mongodb://mongodb:27017/chatbot
    depends_on:
      - mongodb
    ports:
      - "8000:8000"

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - flask-app

volumes:
  mongo-data:
