services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask-app
    environment:
      MONGODB_CONNECTION_URI: mongodb://mongodb:27017
    depends_on:
      - mongodb
    ports:
      - "8000:8000"

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - flask-app

volumes:
  mongo-data:
